# main menu navigation | 导航栏
menu:
  home: /
  archives: /archives
  about: /about
  message: /message
  search: /search
  # rss: /atom.xml

# Personal profile | 个人简介
author: 树寒
blogname: 树寒的博客  # Logo and website name | logo及网站名称
notice: <p>吾将上下而求索!<br></p> # This is the announcement section of aside on the right | 公告部分
email:   # email

# Site introduction | 站点介绍，用于申请友链
sitename: 树寒的博客  # 站点名称
sitelink: https://shuxhan.com # 站点链接
siteimg: https://shuxhan.gitee.io/img/2020.12/han.png # 站点头像
siteintroduction: 吾将上下而求索！  # 站点介绍

# 网站icon图标
favicon: https://shuxhan.gitee.io/img/2021.01/favicon.png

# Whether to display categories and tags on the home page | 首页目录是否显示分类标签
show_post_category: true
show_post_tags: true

# aside栏
sidebar: true
widgets: 
  - notice  # 公告
  - category  # 分类
  - tag # 标签
  - recent_posts  # 最近文章
  - archive # 归档
  - links # 友情链接
  - attention # 通知

links:  # 友情链接
  - title: "树寒的博客"
    url: https://shuxhan.com

# footer link | 底部链接
navs: # 导航
  - title: "GitHub"
    url: https://github.com

community:  # 社区论坛
  - title: "掘金"
    url: https://juejin.cn

file:   # 官方文档
  - title: "hexo官网"
    url: https://hexo.io

# Station construction time | 建站时间
buildtime: 2020   # year
datetime: 06/14/2020 12:00:00   # specific time, The station has been running safely | 本站已安全运行时间

# 代码复制
codeblock: 
  copy_button: 
    enable: true
    result: true
  copyright:
    enable: false
    content: \n/**\n* 感谢您复制代码，使用代码请注明引用出处\n* kajweb @ https://shuxhan.com\n*/


# This topic is built into the twikoo comment system |  本主题内置的是twikoo评论系统
# Official documents | 官方文档 https://twikoo.js.org/
# twikoo:
envID:  # 环境变量
visitors: false  # 是否显示文章阅读量
